version: '3.8'

services:
  backend:
    build: ./backend
    container_name: festival-backend
    restart: always
    volumes:
      - ./backend/app:/app/app
      - ./backend/seed.py:/app/seed.py
      - ./lineup.csv:/app/lineup.csv
      - ./parsed.csv:/app/parsed.csv
      - sqlite_data:/app/instance
      - ./logs:/app/logs
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=wsgi.py
      - FLASK_DEBUG=1
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  frontend:
    build: ./frontend
    container_name: festival-frontend
    restart: always
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
      - ./logs:/app/logs
    ports:
      - "3003:3003"
    environment:
      - PORT=3003
      - REACT_APP_API_URL=https://ubbi.fromseb.com/api
    depends_on:
      - backend
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  sqlite_data: 